//   departments name
export const departments = [
    { name: "Public Administration", sortName: "PAD" },
    { name: "Computer Science and Engineering", sortName: "CSE" },
    { name: "Electrical and Electronic Engineering", sortName: "EEE" },
    { name: "Electronics and Telecommunication Engineering", sortName: "ETE" },
    { name: "Applied Chemistry and Chemical Engineering", sortName: "ACCE" },
    { name: "Civil Engineering", sortName: "CE" },
    { name: "Food and Agroprocess Engineering", sortName: "FAE" },
    { name: "Architecture", sortName: "ARCH" },
    { name: "Mathematics", sortName: "MATH" },
    { name: "Statistics", sortName: "STAT" },
    { name: "Chemistry", sortName: "CHEM" },
    { name: "Physics", sortName: "PHY" },
    { name: "Environmental Science & Disaster Management", sortName: "ESD" },
    { name: "Pharmacy", sortName: "PHR" },
    { name: "Biotechnology and Genetic Engineering", sortName: "BGE" },
    { name: "Biochemistry and Molecular Biology", sortName: "BMB" },
    { name: "Psychology", sortName: "PSY" },
    { name: "Botany", sortName: "BOT" },
    { name: "English", sortName: "ENG" },
    { name: "Bangla", sortName: "BAN" },
    { name: "Sociology", sortName: "SOC" },
    { name: "International Relations", sortName: "IR" },
    { name: "Economics", sortName: "ECO" },
    { name: "Political Science", sortName: "PS" },
    { name: "Management Studies", sortName: "MGT" },
    { name: "Accounting and Information Systems", sortName: "AIS" },
    { name: "Marketing", sortName: "MKT" },
    { name: "Finance and Banking", sortName: "FAB" },
    { name: "Tourism and Hospitality Management", sortName: "THM" },
    { name: "Law", sortName: "LAW" },
    { name: "Agriculture", sortName: "AGR" },
    { name: "Fisheries and Marine Bioscience", sortName: "FMB" },
    { name: "Livestock Science and Veterinary Medicine", sortName: "LSVM" },
  ];