import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./../components/shared/Navbar/Navbar";
import AuthProvider from "./../providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Modhumoti Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="winter" className="font-roboto">
      <AuthProvider>
        <body className={inter.className}>
          <header className="sticky top-0 z-50">
            <Navbar />
          </header>
          <main>{children}</main>
          <ToastContainer />
        </body>
      </AuthProvider>
    </html>
  );
}
