import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./../components/shared/Navbar/Navbar";
// import AuthProvider from "./../providers/AuthProvider";
// import { SessionProvider } from 'next-auth/react';
const inter = Inter({ subsets: ["latin"] });

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/shared/Footer/Footer";

export const metadata: Metadata = {
  title: "Modhumoti Library",
  description: "Generated by create next app",
};

import {auth} from '@/auth'

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <html lang="en" data-theme="winter" className="font-roboto">
      {/* <SessionProvider> */}
        <body className={inter.className}>
          <header className="sticky top-0 z-50">
            <Navbar session={session} />
          </header>
          <main className="min-h-screen">{children}</main>
          <footer>
            <Footer />
          </footer>
          <ToastContainer />
        </body>
        {/* </SessionProvider> */}
    </html>
  );
}
